# fly.toml file generated for harry-tuttle on 2022-10-01T18:29:31-05:00

app = "harry-tuttle"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  builder = "heroku/buildpacks:20"

[env]
  PORT = "5000"
  PERSISTENT_FILE_PATH = "/storage"
  DBPATH = "/storage/hunt2022_stats.db"


[experimental]
  allowed_public_ports = []
  auto_rollback = true


[[services]]

[mounts]
source="tuttledb"
destination="/storage"

